/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PhieuNhan;

import DAO.BangDichVuDao;
import DAO.BangDichVuUse;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import java.util.Date;
import java.sql.SQLException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import thanhtoan.TaoHoaDon;
import thanhtoan.ThemKhachHangUser;
import thanhtoan.ThemKhachhangDao;

/**
 *
 * @author dauxu
 */
public class PhieuNhan extends javax.swing.JFrame {

    BangDichVuDao dao = new BangDichVuDao();
    /**
     * Creates new form PhieuNhan
     */
    private JTable table;
    private JPanel panel;
    private JFrame tableFrame;
    private JButton button;

    public String setKh() {
        String kh = new DAO.BangDichVuDao().MaKH();
        return kh;
    }

    public PhieuNhan() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachPhieu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDphieunhan = new javax.swing.JTextField();
        txtXe = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        txtKhachHang = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnAddPhieu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnIDphieuNhan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtTimeOut = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(1191, 537));
        jPanel10.setRequestFocusEnabled(false);

        tblDanhSachPhieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Khách Hàng ", "Xe", "Thời Gian ", "Hẹn ", "Tình trạng "
            }
        ));
        tblDanhSachPhieu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblDanhSachPhieuAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblDanhSachPhieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachPhieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachPhieu);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách phiếu nhận ");

        jLabel2.setText("Id Phiếu Nhận  : ");

        jLabel3.setText("Khách hàng : ");

        jLabel4.setText("Mã Xe :");

        jLabel5.setText("Thời Gian : ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Thông tin phiếu nhận");

        jButton1.setText("Cập Nhật ");

        jButton2.setText("Xóa Phiếu ");

        btnAddPhieu.setText("Thêm Phiếu");
        btnAddPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPhieuActionPerformed(evt);
            }
        });

        jLabel7.setText("Thời Gian Hẹn : ");

        btnIDphieuNhan.setText("+");
        btnIDphieuNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDphieuNhanActionPerformed(evt);
            }
        });

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtTimeOut.setDateFormatString("yyyy, MMM d");

        jLabel8.setText("Tình trạng xe :");

        jScrollPane2.setViewportView(txtNoiDung);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIDphieunhan)
                                    .addComponent(txtKhachHang)
                                    .addComponent(txtXe)
                                    .addComponent(txtTime)
                                    .addComponent(txtTimeOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(btnAddPhieu))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(154, 154, 154)
                                        .addComponent(jButton2)))
                                .addGap(45, 45, 45)
                                .addComponent(jButton1)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(btnLamMoi)
                                .addGap(42, 42, 42))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIDphieuNhan)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4))
                                .addContainerGap())))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIDphieunhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIDphieuNhan))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jButton3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jButton4))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddPhieu)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(btnLamMoi))
                        .addGap(65, 65, 65))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSachPhieuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblDanhSachPhieuAncestorAdded

        try {
            // TODO add your handling code here:
            fillDateTable();
        } catch (SQLException ex) {
            Logger.getLogger(PhieuNhan.class.getName()).log(Level.SEVERE, null, ex);
        }
//         java.sql.Date.valueOf(txtTime.getText()), txtTimeOut.getDate()
    }//GEN-LAST:event_tblDanhSachPhieuAncestorAdded

    private void btnAddPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPhieuActionPerformed
        new BangDichVuDao().AddPhieu(txtIDphieunhan.getText(), txtXe.getText(), txtKhachHang.getText(), java.sql.Date.valueOf(txtTime.getText()), txtTimeOut.getDate(), txtNoiDung.getText());
    }//GEN-LAST:event_btnAddPhieuActionPerformed

    private void tblDanhSachPhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachPhieuMouseClicked
        // TODO add your handling code here:
        int myindex = tblDanhSachPhieu.getSelectedRow();
        txtIDphieunhan.setText(tblDanhSachPhieu.getValueAt(myindex, 0).toString());
        txtKhachHang.setText(tblDanhSachPhieu.getValueAt(myindex, 1).toString());
        txtXe.setText(tblDanhSachPhieu.getValueAt(myindex, 2).toString());
        txtTime.setText(tblDanhSachPhieu.getValueAt(myindex, 3).toString());
        txtTimeOut.setDate(java.sql.Date.valueOf(tblDanhSachPhieu.getValueAt(myindex, 4).toString()));
        txtNoiDung.setText(tblDanhSachPhieu.getValueAt(myindex, 5).toString());
    }//GEN-LAST:event_tblDanhSachPhieuMouseClicked

    private void btnIDphieuNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDphieuNhanActionPerformed
        // TODO add your handling code here:
        txtIDphieunhan.setEditable(false);
        txtIDphieunhan.setText(setKh());
    }//GEN-LAST:event_btnIDphieuNhanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        btnKhachHang();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        reset();

    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Date a = java.sql.Date.valueOf(LocalDate.now());
        txtTime.setText(String.valueOf(a));
    }//GEN-LAST:event_jButton4ActionPerformed
    public void fillDateTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachPhieu.getModel();
        model.setRowCount(0);
        for (BangDichVuUse sp : dao.getAllSanPham()) {
            Object rowData[] = new Object[6];
            rowData[0] = sp.getID();
            rowData[1] = sp.getKH();
            rowData[2] = sp.getIdcar();
            rowData[3] = sp.getTime();
            rowData[4] = sp.getTimeout();
            rowData[5] = sp.getNoidung();
            model.addRow(rowData);
        }
    }

    private void btnKhachHang() {

        tableFrame = new JFrame("Khách Hàng ");
        table = new JTable();
//          button = new JButton();
        String[] columnNames = {"Name", "SoDienThoai", "Tên Xe ", "Mã Xe"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        try {
            ThemKhachhangDao Kh = new ThemKhachhangDao();
            for (ThemKhachHangUser sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[4];
                rowData[0] = sp.getHoten();
                rowData[1] = sp.getSdt();
                rowData[2] = sp.getTenXe();
                rowData[3] = sp.getIdcar();
                model.addRow(rowData);
            }
            table.setModel(model);

            JButton btnThoat = new JButton("Thoát");
            btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    tableFrame.dispose(); // Close the JFrame
                }
            });
            tableFrame.add(btnThoat, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(table);
            tableFrame.add(scrollPane);

            tableFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            tableFrame.setLocationRelativeTo(null);
            tableFrame.pack();
            tableFrame.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            // Handle any other exceptions here
        }
        button = new JButton();
        table.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int myindex = table.getSelectedRow();
                txtKhachHang.setText(table.getValueAt(myindex, 0).toString());
//                txtSdt.setText(table.getValueAt(myindex, 1).toString());
                txtXe.setText(table.getValueAt(myindex, 3).toString());
            }
        });

    }

    public void reset() {
        txtIDphieunhan.setText("");
        txtKhachHang.setText("");
        txtTime.setText("");
        txtTimeOut.setDateFormatString("");
        txtXe.setText("");
        txtNoiDung.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhieuNhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPhieu;
    private javax.swing.JButton btnIDphieuNhan;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDanhSachPhieu;
    private javax.swing.JTextField txtIDphieunhan;
    private javax.swing.JTextField txtKhachHang;
    private javax.swing.JTextPane txtNoiDung;
    private javax.swing.JTextField txtTime;
    private com.toedter.calendar.JDateChooser txtTimeOut;
    private javax.swing.JTextField txtXe;
    // End of variables declaration//GEN-END:variables
}
