/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thanhtoan;

import duanmau1.TrangChu;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dauxu
 */
public class HoaDonLE extends javax.swing.JFrame {

    private JTable table;
    private JPanel panel;
    private JFrame tableFrame;
    private JButton button;
// .........................
    //  Thêm Linh Kiện 
    private JTable tablelk;
    private JPanel panellk;
    private JButton buttonlk;
    private JFrame framelk;

//    Thêm Phiếu Nhận 
    private JTable tablepn;
    private JFrame framepn;
    private JButton buttonpn;
// Thêm Nhân Viên 
    private JTable tablenv;
    private JFrame framenv;
    private JButton buttonnv;
    // Thêm Phiếu Nhận
    private JTable tabletpn;
    private JFrame frametpn;
    private JButton buttontpn;
//    Them Cong 
    private JTable tableCong;
    private JFrame framecong;
    private JButton buttonCong;
/////////////
//    Giờ 
    public static String dataTime;
// Người Thanh Toán 
    public static String dataNTT;
//    Số Điện Thoại 
    public static String dataSDt;
//     Mã Hóa Đơn 
    public static String dataMHD;
//      Tên Khách Hàng 
    public static String dataTKH;
//       Mã Phiếu Nhận 
    public static String dataMPN;
//        Số điện thoại khách hàng 
    public static String dataSDTKH;
//        Biển Số Xe 
    public static String dataBSX;
//        Tên Xe 
    public static String dataTenXe;
//        Ngày Đưa Vào 
    public static String datatimein;
//        Ngày Trả Xe 
    public static String dataout;

    DefaultTableModel LinhKien = new DefaultTableModel();
    ArrayList<Object> ds = new ArrayList<>();

    public String setKh() {
        String kh = new thanhtoan.ThanhToanUse().MaKH();
        return kh;
    }

    /**
     * Creates new form HoaDonLE
     */
    public HoaDonLE() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnKhachHang = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnLinhKien = new javax.swing.JButton();
        lblClock = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMhd = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        txtXe = new javax.swing.JTextField();
        txtKhachHang = new javax.swing.JTextField();
        txtTT = new javax.swing.JTextField();
        txtNvpt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLinhKien = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtTongTienTT = new javax.swing.JTextField();
        txtThemMa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtCong = new javax.swing.JTextField();
        btnCongsua = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tạo Phiếu ");

        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnKhachHang.setText("Khách Hàng ");
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnNhanVien.setText("Nhân Viên ");
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnLinhKien.setText("Linh Kiện ");
        btnLinhKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinhKienActionPerformed(evt);
            }
        });

        lblClock.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hóa Đơn ");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Mã Hóa Đơn : ");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Khách hàng : ");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Xe : ");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nhân Viên Phụ Trách : ");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tình Trạng : ");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Số điện thoại:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Ghi Chú : ");

        txtMhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMhdActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtNoiDung);

        tblLinhKien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TT", "Nhà Cung Cấp ", "Linh Kiện ", "Đơn Giá ", "Số Lượng", "Tổng tiền "
            }
        ));
        jScrollPane2.setViewportView(tblLinhKien);

        jLabel10.setText("Tổng tiền thanh toán  : ");

        txtThemMa.setText("+");
        txtThemMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemMaActionPerformed(evt);
            }
        });

        jLabel11.setText("Công sửa chữa: ");

        btnCongsua.setText("+");
        btnCongsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongsuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(txtXe, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMhd, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKhachHang, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtThemMa)
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSdt, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(txtNvpt)
                                    .addComponent(txtCong))
                                .addGap(18, 18, 18)
                                .addComponent(btnCongsua))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtTongTienTT, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMhd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThemMa)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNvpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCongsua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTienTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        btnNew.setText("Làm Mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        jButton1.setText("Hủy tạo ");

        jButton2.setText("Thanh Toán ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        TrangChu trangchu = new TrangChu();
//        //         TaoHoaDon.dispose();
//        trangchu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed

        btnKhachHang();
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        btnThemNhanVien();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnLinhKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinhKienActionPerformed
        // TODO add your handling code here:
        btnThemLinhKien();
    }//GEN-LAST:event_btnLinhKienActionPerformed

    private void txtMhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMhdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMhdActionPerformed

    private void txtThemMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemMaActionPerformed
        // TODO add your handling code here:
        txtMhd.setEditable(false);
        txtMhd.setText(setKh());
    }//GEN-LAST:event_txtThemMaActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        LamMoi();
    }//GEN-LAST:event_btnNewActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dataNTT = txtNvpt.getText();
        //        dataSDt =.getText();
        dataMHD = txtMhd.getText();
//        dataMPN = txtMpn.getText();
        //        dataBSX = .getText();
//        dataMPN = txtMpn.getText();
        dataSDTKH = txtSdt.getText();
        dataTKH = txtKhachHang.getText();
//        dataout = txtTimeHen.getText();
        dataTime = lblClock.getText();
        dataTenXe = txtXe.getText();
        //          LinhKien = (DefaultTableModel) tblLinhKien.getModel();
        HoaDon hoadon = new HoaDon();
        hoadon.fillDateTable(ds);
        hoadon.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCongsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongsuaActionPerformed
        // TODO add your handling code here:
        ThemCong();
    }//GEN-LAST:event_btnCongsuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonLE().setVisible(true);
            }
        });
    }

    private void ThemCong() {
        framecong = new JFrame("Cong ");
        tableCong = new JTable();
//          button = new JButton();
        String[] columnNames = {"Id", "Tên Công", " Giá "};
        DefaultTableModel modelllllll = new DefaultTableModel(columnNames, 0);

        try {
            CongDao Kh = new CongDao();
            for (CongUse sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[7];
                rowData[0] = sp.getId();
                rowData[1] = sp.getTenCong();
                rowData[2] = sp.getGia();

//                rowData[6] = sp.getTongTien();
                modelllllll.addRow(rowData);
            }
            tableCong.setModel(modelllllll);

            JButton btnThoat = new JButton("Thoát");
            btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    framecong.dispose(); // Close the JFrame
                }
            });
            framecong.add(btnThoat, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(tableCong);
            framecong.add(scrollPane);

            framecong.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            framecong.setLocationRelativeTo(null);
            framecong.pack();
            framecong.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            // Handle any other exceptions here
        }
        buttonCong = new JButton();
        tableCong.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int myindex = tableCong.getSelectedRow();
                txtCong.setText(tableCong.getValueAt(myindex, 2).toString());

            }
        });
    }

    public void LamMoi() {
        txtKhachHang.setText("");
        txtSdt.setText("");
        txtXe.setText("");
//        txtMpn.setText("");
//        txtTimeHen.setText("");
        txtTT.setText("");
        txtNvpt.setText("");
        DefaultTableModel model = (DefaultTableModel) tblLinhKien.getModel();
        model.setRowCount(0);
        String[] columnNames = {"id", "Tên Nhà Cung Cấp", "Đơn Giá", "Số Lượng", "Tổng Tiền"};
        DefaultTableModel newModel = new DefaultTableModel(columnNames, 0);
        tblLinhKien.setModel(newModel);
        txtNoiDung.setText("");
        txtTongTienTT.setText("");
    }

    private void btnThemNhanVien() {
        framenv = new JFrame("Linh Kiện  ");
        tablenv = new JTable();
        String[] columnNames = {"Tên Nhân Viên ", "Giới Tính  ", " Địa Chỉ   "};
        DefaultTableModel modell = new DefaultTableModel(columnNames, 0);

        try {
            NhanVienUse Kh = new NhanVienUse();
            for (NhanVienDao sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[4];
                rowData[0] = sp.getHoten();
                rowData[1] = sp.isGioitinh();
                rowData[2] = sp.getSdt();
                modell.addRow(rowData);
            }
            tablenv.setModel(modell);

            JButton btnThoat = new JButton("Thoát");
            btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    framenv.dispose(); // Close the JFrame
                }
            });
            framenv.add(btnThoat, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(tablenv);
            framenv.add(scrollPane);

            framenv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            framenv.setLocationRelativeTo(null);
            framenv.pack();
            framenv.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            // Handle any other exceptions here
        }
        buttonnv = new JButton();
        tablenv.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int myindex = tablenv.getSelectedRow();
                txtNvpt.setText(tablenv.getValueAt(myindex, 0).toString());

//             txtXe.setText(tablelk.getValueAt(myindex, 3).toString());
            }
        });
    }

    private void btnThemLinhKien() {
        framelk = new JFrame("Linh Kiện  ");
        tablelk = new JTable();
        String[] columnNames = {"Mã phiếu sửa  ", "Tên Nhà Cung Cấp ", " Linh Kiện  ", " Đơn Giá  ", " Số Lượng ", "Giá Bán "};
        DefaultTableModel modell = new DefaultTableModel(columnNames, 0);
//        Connection conn = null;
//        Statement sttm = null;
//        ResultSet rs = null;
        PreparedStatement pta = null;
        try {

            ThemlinhkienDao Kh = new ThemlinhkienDao();
            for (ThemlinhkienUse sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[6];
                rowData[0] = sp.getMasua();
                rowData[1] = sp.getTencc();
                rowData[2] = sp.getTenPT();
                rowData[3] = sp.getGia();
                rowData[4] = sp.getSoluong();
                rowData[5] = sp.getGiaban();
                modell.addRow(rowData);
//                LinhKien.addRow(rowData);
//                ds.add(rowData);
            }
            tablelk.setModel(modell);

            JButton btnThem = new JButton("Thêm ");
            btnThem.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {

                    int nextRowID = tblLinhKien.getRowCount() + 1;
                    int selectedRowIndex = tablelk.getSelectedRow();

                    if (selectedRowIndex >= 0) {
                        String nhacungcap = tablelk.getValueAt(selectedRowIndex, 1).toString();
                        String linhkien = tablelk.getValueAt(selectedRowIndex, 2).toString();

                        int soluong = Integer.parseInt(tablelk.getValueAt(selectedRowIndex, 4).toString());
                        double giaban = Double.parseDouble(tablelk.getValueAt(selectedRowIndex, 3).toString());

                        String inputSoluong = JOptionPane.showInputDialog(framelk, "Nhập số lượng:", "Nhập Số Lượng", JOptionPane.PLAIN_MESSAGE);

                        if (inputSoluong != null) {
                            int soluongNhap = Integer.parseInt(inputSoluong);
                            int soluongHienCo = Integer.parseInt(tablelk.getValueAt(selectedRowIndex, 4).toString());

                            if (soluongNhap > 0 && soluongNhap <= soluongHienCo) {
                                double total =soluongNhap *giaban ;

                                DefaultTableModel destModel = (DefaultTableModel) tblLinhKien.getModel();
                                destModel.addRow(new Object[]{nextRowID, nhacungcap, linhkien, giaban, soluongNhap, total});
                                 ds.add(new Object[]{  nhacungcap, linhkien, giaban, soluongNhap, total});
                                Connection conn = null;
                                PreparedStatement pta = null;
                                try {
                                    String SQL = "UPDATE PHUTUNG SET soluong = soluong - ? WHERE Soluong = ?";
                                    conn = data.ConnecSQL.getDBConnect();
                                    pta = conn.prepareStatement(SQL);
//                              
                                    pta.setInt(1, soluongNhap);
                                    pta.setInt(2, soluongNhap);
                                    pta.executeUpdate();
                                } catch (SQLException ex) {
                                    Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
                                } finally {

                                    if (pta != null) {
                                        try {
                                            pta.close();
                                        } catch (SQLException ex) {
                                            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                    }
                                }
                            } else {
                                JOptionPane.showMessageDialog(framelk, "Số lượng không hợp lệ hoặc vượt quá số lượng hiện có!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                            }
                        }

                    }

                }
            });
            framelk.add(btnThem, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(tablelk);
            framelk.add(scrollPane);

            framelk.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            framelk.setLocationRelativeTo(null);
            framelk.pack();
            framelk.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            // Handle any other exceptions here
        }
    }

    private void btnKhachHang() {

        tableFrame = new JFrame("Khách Hàng ");
        table = new JTable();
//          button = new JButton();
        String[] columnNames = {"Name", "SoDienThoai", "Tên Xe ", "Biển Số "};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        try {
            ThemKhachhangDao Kh = new ThemKhachhangDao();
            for (ThemKhachHangUser sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[4];
                rowData[0] = sp.getHoten();
                rowData[1] = sp.getSdt();
                rowData[2] = sp.getTenXe();
                rowData[3] = sp.getBienso();
                model.addRow(rowData);
            }
            table.setModel(model);

            JButton btnThoat = new JButton("Thoát");
            btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    tableFrame.dispose(); // Close the JFrame
                }
            });
            tableFrame.add(btnThoat, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(table);
            tableFrame.add(scrollPane);

            tableFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            tableFrame.setLocationRelativeTo(null);
            tableFrame.pack();
            tableFrame.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            // Handle any other exceptions here
        }
        button = new JButton();
        table.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int myindex = table.getSelectedRow();
                txtKhachHang.setText(table.getValueAt(myindex, 0).toString());
                txtSdt.setText(table.getValueAt(myindex, 1).toString());
                txtXe.setText(table.getValueAt(myindex, 2).toString());
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCongsua;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnLinhKien;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClock;
    private javax.swing.JTable tblLinhKien;
    private javax.swing.JTextField txtCong;
    private javax.swing.JTextField txtKhachHang;
    private javax.swing.JTextField txtMhd;
    private javax.swing.JTextPane txtNoiDung;
    private javax.swing.JTextField txtNvpt;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTT;
    private javax.swing.JButton txtThemMa;
    private javax.swing.JTextField txtTongTienTT;
    private javax.swing.JTextField txtXe;
    // End of variables declaration//GEN-END:variables
}
