/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thanhtoan;

import duanmau1.TrangChu;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dauxu
 */
public class TaoHoaDon extends javax.swing.JFrame {
    private JButton exitButton;
//    Thêm Khách Hàng 
    private JTable table;
    private JPanel panel;
    private JFrame tableFrame;
    private JButton button;
// .........................
    //  Thêm Linh Kiện 
    private JTable tablelk;
    private JPanel panellk;
    private JButton buttonlk;
    private JFrame framelk;

//    Thêm Phiếu Nhận 
    private JTable tablepn;
    private JFrame framepn;
    private JButton buttonpn;
// Thêm Nhân Viên 
    private JTable tablenv;
    private JFrame framenv;
    private JButton buttonnv;
    // Thêm Phiếu Nhận
    private JTable tabletpn;
    private JFrame frametpn;
    private JButton buttontpn;
//    Them Cong 
    private JTable tableCong;
    private JFrame framecong;
    private JButton buttonCong;
/////////////
//    Giờ 
    public static String dataTime;
// Người Thanh Toán 
    public static String dataNTT;
//    Số Điện Thoại 
    public static String dataSDt;
//     Mã Hóa Đơn 
    public static String dataMHD;
//      Tên Khách Hàng 
    public static String dataTKH;
//       Mã Phiếu Nhận 
    public static String dataMPN;
//        Số điện thoại khách hàng 
    public static String dataSDTKH;
//        Biển Số Xe 
    public static String dataBSX;
//        Tên Xe 
    public static String dataTenXe;
//        Ngày Đưa Vào 
    public static String datatimein;
//        Ngày Trả Xe 
    public static String dataout;
// tinh trang xe 
    public static String dataTT;
//    cong sua
    public static String dataCong;
//    phieu sua
    public static String dataSua;
//    tongthanhtoan
    public static String dataTongTien;
    DefaultTableModel LinhKien = new DefaultTableModel();
    ArrayList<Object> ds = new ArrayList<>();

    public String setKh() {
        String kh = new thanhtoan.ThanhToanUse().MaKH();
        return kh;
    }

    public TaoHoaDon() {
        initComponents();
        setLocationRelativeTo(null);
//        modellkien = (DefaultTableModel) tblLinhKien.getModel();
        clock();
//         exitButton.setText("Thoát");
//        LinhKien = (DefaultTableModel) tblLinhKien.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnNhanVien = new javax.swing.JButton();
        btnLinhKien = new javax.swing.JButton();
        btnPhieuNhan = new javax.swing.JButton();
        btnPhieuSua = new javax.swing.JButton();
        lblClock = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMhd = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        txtTimeHen = new javax.swing.JTextField();
        txtMpn = new javax.swing.JTextField();
        txtXe = new javax.swing.JTextField();
        txtKhachHang = new javax.swing.JTextField();
        txtTT = new javax.swing.JTextField();
        txtNvpt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLinhKien = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtTongTienTT = new javax.swing.JTextField();
        txtThemMa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtCong = new javax.swing.JTextField();
        btnCongsua = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtNhan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtMaSua = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lblTongLK = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tạo Phiếu ");

        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNhanVien.setText("Nhân Viên ");
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnLinhKien.setText("Linh Kiện ");
        btnLinhKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinhKienActionPerformed(evt);
            }
        });

        btnPhieuNhan.setText("Phiếu Hẹn");
        btnPhieuNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuNhanActionPerformed(evt);
            }
        });

        btnPhieuSua.setText("Phiếu Sửa");
        btnPhieuSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuSuaActionPerformed(evt);
            }
        });

        lblClock.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton4.setText("Linh Kiện Lẻ ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPhieuSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPhieuNhan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLinhKien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnPhieuNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnPhieuSua, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hóa Đơn ");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Mã Hóa Đơn : ");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Khách hàng : ");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Xe : ");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Thời Gian Hẹn: ");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Mã Phiếu Hẹn : ");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nhân Viên Phụ Trách : ");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tình Trạng : ");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Số điện thoại:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Ghi Chú : ");

        txtMhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMhdActionPerformed(evt);
            }
        });

        txtTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTTActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtNoiDung);

        tblLinhKien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TT", "Nhà Cung Cấp ", "Linh Kiện ", "Đơn Giá ", "Số Lượng", "Tổng tiền "
            }
        ));
        jScrollPane2.setViewportView(tblLinhKien);

        jLabel10.setText("Tổng tiền thanh toán  : ");

        txtTongTienTT.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtTongTienTTAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtTongTienTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienTTActionPerformed(evt);
            }
        });

        txtThemMa.setText("+");
        txtThemMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemMaActionPerformed(evt);
            }
        });

        jLabel11.setText("Công sửa chữa: ");

        txtCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCongActionPerformed(evt);
            }
        });

        btnCongsua.setText("+");
        btnCongsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongsuaActionPerformed(evt);
            }
        });

        jLabel13.setText("Thời gian nhận : ");

        jLabel15.setText("Mã Sửa: ");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Tổng Linh Kiện : ");

        lblTongLK.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaSua)
                                    .addComponent(txtMhd)
                                    .addComponent(txtKhachHang)
                                    .addComponent(txtXe)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(txtThemMa)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSdt, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(txtMpn)
                                    .addComponent(txtTimeHen)
                                    .addComponent(txtNvpt)
                                    .addComponent(txtCong))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCongsua))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtTT, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTongTienTT, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(lblTongLK, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMhd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThemMa))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtTimeHen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNvpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15)
                    .addComponent(txtMaSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCongsua))
                    .addComponent(txtNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTongLK, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTongTienTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        btnNew.setText("Làm Mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        jButton1.setText("Hủy tạo ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thanh Toán ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnKhachHang.setText("Khách Hàng ");
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed

        btnKhachHang();
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        btnThemNhanVien();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnPhieuNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuNhanActionPerformed
        // TODO add your handling code here:
        btnPhieuNhan();
    }//GEN-LAST:event_btnPhieuNhanActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        LamMoi();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnPhieuSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuSuaActionPerformed
        // TODO add your handling code here:
        btnThemPhieuNhan();
    }//GEN-LAST:event_btnPhieuSuaActionPerformed

    private void txtMhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMhdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMhdActionPerformed

    private void txtThemMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemMaActionPerformed
        // TODO add your handling code here:
        txtMhd.setEditable(false);
        txtMhd.setText(setKh());
    }//GEN-LAST:event_txtThemMaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dataNTT = txtNvpt.getText();
//        dataSDt =.getText();
        dataMHD = txtMhd.getText();
        dataMPN = txtMpn.getText();
//        dataBSX = .getText();

        dataMPN = txtMpn.getText();
        dataSDTKH = txtSdt.getText();
        dataTKH = txtKhachHang.getText();
        dataout = txtTimeHen.getText();
        dataTime = lblClock.getText();
        dataTenXe = txtXe.getText();
        dataTT = txtTT.getText();
        datatimein = txtNhan.getText();
        dataCong = txtCong.getText();
        dataSua = txtMaSua.getText();
        dataTongTien = txtTongTienTT.getText();
//          LinhKien = (DefaultTableModel) tblLinhKien.getModel();
        HoaDon hoadon = new HoaDon();
        hoadon.fillDateTable(ds);
        hoadon.setVisible(true);
//        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        TrangChu trangchu = new TrangChu();
////         TaoHoaDon.dispose();
//        trangchu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCongsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongsuaActionPerformed
        // TODO add your handling code here:
        ThemCong();
    }//GEN-LAST:event_btnCongsuaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTTActionPerformed

    private void txtCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCongActionPerformed

    private void txtTongTienTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienTTActionPerformed
        // TODO add your handling code here:
//        double TienC = Double.parseDouble(txtCong.getText());
//        double Tienn = Double.parseDouble(lblTongLK.getText());
//        double result = TienC + Tienn;
//        txtTongTienTT.setText(result + "");
    }//GEN-LAST:event_txtTongTienTTActionPerformed

    private void txtTongTienTTAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtTongTienTTAncestorAdded
        // TODO add your handling code here:
//        double TienC = Double.parseDouble(txtCong.getText());
//        double Tien = Double.parseDouble(lblTongLK.getText());
//        double result = TienC + Tien;
//         txtTongTienTT.setText(String.valueOf(result));
    }//GEN-LAST:event_txtTongTienTTAncestorAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        linhkienle();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnLinhKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinhKienActionPerformed
        // TODO add your handling code here:
        btnThemLinhKien();
    }//GEN-LAST:event_btnLinhKienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoHoaDon().setVisible(true);
            }
        });
    }

    private void linhkienle() {
        framelk = new JFrame("Linh Kiện Đơn  ");
        tablelk = new JTable();
        framelk.setPreferredSize(new Dimension(800, 300));
        String[] columnNames = {"Tên Nhà Cung Cấp ", " Linh Kiện  ", " Đơn Giá  ", " Số Lượng ", "Giá Bán "};
        DefaultTableModel modell = new DefaultTableModel(columnNames, 0);
        PreparedStatement pta = null;
        try {

            linhkienleDao Kh = new linhkienleDao();
            for (linhkienleUse sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[5];
                rowData[0] = sp.getTencc();
                rowData[1] = sp.getTenPT();
                rowData[2] = sp.getGia();
                rowData[3] = sp.getSoluong();
                rowData[4] = sp.getGiaban();
                modell.addRow(rowData);
            }
            tablelk.setModel(modell);     
            JButton btnThem = new JButton("Thêm ");
            btnThem.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    int nextRowID = tblLinhKien.getRowCount() + 1;
                    int selectedRowIndex = tablelk.getSelectedRow();
                    if (selectedRowIndex >= 0) {
                        String nhacungcap = tablelk.getValueAt(selectedRowIndex, 1).toString();
                        String linhkien = tablelk.getValueAt(selectedRowIndex, 2).toString();
                        int soluong = Integer.parseInt(tablelk.getValueAt(selectedRowIndex, 4).toString());
                        double giaban = Double.parseDouble(tablelk.getValueAt(selectedRowIndex, 5).toString());
                        String inputSoluong = JOptionPane.showInputDialog(framelk, "Nhập số lượng:", "Nhập Số Lượng", JOptionPane.PLAIN_MESSAGE);
                        if (inputSoluong != null) {
                            int soluongNhap = Integer.parseInt(inputSoluong);
                            int soluongHienCo = Integer.parseInt(tablelk.getValueAt(selectedRowIndex, 4).toString());
                            if (soluongNhap > 0 && soluongNhap <= soluongHienCo) {
                                double total = soluongNhap * giaban;
                                DefaultTableModel destModel = (DefaultTableModel) tblLinhKien.getModel();
                                destModel.addRow(new Object[]{nextRowID, nhacungcap, linhkien, giaban, soluongNhap, total});
                                ds.add(new Object[]{nhacungcap, linhkien, giaban, soluongNhap, total});
                                Tien = Tien + total;
                                lblTongLK.setText(String.valueOf(Tien));
                                if (!txtCong.getText().isEmpty()) {
                                    try {
                                        TienCc = Double.parseDouble(txtCong.getText());
                                        result = Tien + TienCc;
                                        txtTongTienTT.setText(String.valueOf(result));
                                    } catch (NumberFormatException ex) {
                                        txtTongTienTT.setText(String.valueOf(result));
                                    }
                                } else {
                                    txtTongTienTT.setText(String.valueOf(result));
                                }
                                Connection conn = null;
                                PreparedStatement pta = null;
                                try {
                                    String SQL = "UPDATE PHUTUNG SET soluong = soluong - ? WHERE Soluong = ?";
                                    conn = data.ConnecSQL.getDBConnect();
                                    pta = conn.prepareStatement(SQL);
                                    pta.setInt(1, soluongNhap);
                                    pta.setInt(2, soluongNhap);
                                    pta.executeUpdate();
                                } catch (SQLException ex) {
                                    Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
                                } finally {

                                    if (pta != null) {
                                        try {
                                            pta.close();
                                        } catch (SQLException ex) {
                                            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                    }
                                }
                            } else {
                                JOptionPane.showMessageDialog(framelk, "Số lượng không hợp lệ hoặc vượt quá số lượng hiện có!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    }
                }
            });
                        JButton btnThoat = new JButton("Thoát");
                   btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    frametpn.dispose(); 
                }
            });
            framelk.add(btnThem, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(tablelk);
            framelk.add(scrollPane);

            framelk.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            framelk.setLocationRelativeTo(null);
            framelk.pack();
            framelk.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ThemCong() {
        framecong = new JFrame(" Công ");
        tableCong = new JTable();
        framecong.setPreferredSize(new Dimension(800, 300));
//          button = new JButton();
        String[] columnNames = {"Id", "Tên Công", " Giá "};
        DefaultTableModel modelllllll = new DefaultTableModel(columnNames, 0);

        try {
            CongDao Kh = new CongDao();
            for (CongUse sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[7];
                rowData[0] = sp.getId();
                rowData[1] = sp.getTenCong();
                rowData[2] = sp.getGia();

//                rowData[6] = sp.getTongTien();
                modelllllll.addRow(rowData);
            }
            tableCong.setModel(modelllllll);

            JButton btnThoat = new JButton("Thoát");
            btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
//                    Tien = Tien + total;
//                    lblTongLK.setText(Tien + "");
//                    TienCc = Double.parseDouble(txtCong.getText());
//                    result = Tien + TienCc;
//                    txtTongTienTT.setText(result + "");
                    if (!txtCong.getText().isEmpty()) {
                        try {
                            TienCc = Double.parseDouble(txtCong.getText());
                            result = Tien + TienCc;
                            txtTongTienTT.setText(String.valueOf(result));
                        } catch (NumberFormatException ex) {
                            // Handle the exception if the input is not a valid number
//                            txtTongTienTT.setText("Invalid Input");
                            txtTongTienTT.setText(String.valueOf(result));
                        }
                    } else {
                        txtTongTienTT.setText(String.valueOf(result));
                    }
                    framecong.dispose(); // Close the JFrame
                }
            });
            framecong.add(btnThoat, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(tableCong);
            framecong.add(scrollPane);

            framecong.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            framecong.setLocationRelativeTo(null);
            framecong.pack();
            framecong.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            // Handle any other exceptions here
        }
        buttonCong = new JButton();
        tableCong.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int myindex = tableCong.getSelectedRow();
                txtCong.setText(tableCong.getValueAt(myindex, 2).toString());

            }
        });
    }

    private void btnPhieuNhan() {

        frametpn = new JFrame("Phiếu  Hẹn ");
        tabletpn = new JTable();
        frametpn.setPreferredSize(new Dimension(800, 300));
//          button = new JButton();
        String[] columnNames = {"Id","Mã Xe", "Thời Gian ", "Hẹn ", " Tình Trạng  "};
        DefaultTableModel modellllll = new DefaultTableModel(columnNames, 0);

        try {
            BtnPhieuNhanDao Kh = new BtnPhieuNhanDao();
            for (BntPhieuNhanUse sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[7];
                rowData[0] = sp.getID();
                rowData[1] = sp.getIdcar();
                rowData[2] = sp.getTime();
                rowData[3] = sp.getTimeout();
                rowData[4] = sp.getTinhTrangIn();
//                rowData[6] = sp.getTongTien();
                modellllll.addRow(rowData);
            }
            tabletpn.setModel(modellllll);

            JButton btnThoat = new JButton("Thoát");
            btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    frametpn.dispose(); // Close the JFrame
                }
            });
            frametpn.add(btnThoat, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(tabletpn);
            frametpn.add(scrollPane);

            frametpn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frametpn.setLocationRelativeTo(null);
            frametpn.pack();
            frametpn.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            // Handle any other exceptions here
        }
        buttontpn = new JButton();
        tabletpn.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int myindex = tabletpn.getSelectedRow();
                txtMpn.setText(tabletpn.getValueAt(myindex, 0).toString());
                txtTimeHen.setText(tabletpn.getValueAt(myindex, 3).toString());
//                txtTT.setText(tabletpn.getValueAt(myindex, 5).toString());
                txtNhan.setText(tabletpn.getValueAt(myindex, 2).toString());
            }
        });

    }

    private void btnKhachHang() {

        tableFrame = new JFrame("Khách Hàng ");
        table = new JTable();
        tableFrame.setPreferredSize(new Dimension(800, 300));
//          button = new JButton();
        String[] columnNames = {"Name", "SoDienThoai", "Tên Xe ", "Biển Số "};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        try {
            ThemKhachhangDao Kh = new ThemKhachhangDao();
            for (ThemKhachHangUser sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[4];
                rowData[0] = sp.getHoten();
                rowData[1] = sp.getSdt();
                rowData[2] = sp.getTenXe();
                rowData[3] = sp.getBienso();
                model.addRow(rowData);
            }
            table.setModel(model);

            JButton btnThoat = new JButton("Thoát");
            btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    tableFrame.dispose(); // Close the JFrame
                }
            });
            tableFrame.add(btnThoat, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(table);
            tableFrame.add(scrollPane);

            tableFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            tableFrame.setLocationRelativeTo(null);
            tableFrame.pack();
            tableFrame.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            // Handle any other exceptions here
        }
        button = new JButton();
        table.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int myindex = table.getSelectedRow();
                txtKhachHang.setText(table.getValueAt(myindex, 0).toString());
                txtSdt.setText(table.getValueAt(myindex, 1).toString());
                txtXe.setText(table.getValueAt(myindex, 2).toString());
            }
        });

    }
    double Tien = 0;
    double TienCc = 0;
    double result = 0;

    private void btnThemLinhKien() {
        framelk = new JFrame("Linh Kiện  ");
        tablelk = new JTable();
        framelk.setPreferredSize(new Dimension(800, 300));
        String[] columnNames = {"Mã phiếu sửa  ", "Tên Nhà Cung Cấp ", " Linh Kiện  ", " Đơn Giá  ", " Số Lượng ", "Giá Bán "};
        DefaultTableModel modell = new DefaultTableModel(columnNames, 0);

        PreparedStatement pta = null;
        try {

            ThemlinhkienDao Kh = new ThemlinhkienDao();
            for (ThemlinhkienUse sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[6];
                rowData[0] = sp.getMasua();
                rowData[1] = sp.getTencc();
                rowData[2] = sp.getTenPT();
                rowData[3] = sp.getGia();
                rowData[4] = sp.getSoluong();
                rowData[5] = sp.getGiaban();
                modell.addRow(rowData);
            }
            tablelk.setModel(modell);
            JButton btnThoat = new JButton("Thoát");
            btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    frametpn.dispose(); // Close the JFrame
                }
            });
            buttonlk = new JButton();
            JButton btnThem = new JButton("Thêm ");
            btnThem.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {

                    int nextRowID = tblLinhKien.getRowCount() + 1;
                    int selectedRowIndex = tablelk.getSelectedRow();

                    if (selectedRowIndex >= 0) {
                        String nhacungcap = tablelk.getValueAt(selectedRowIndex, 1).toString();
                        String linhkien = tablelk.getValueAt(selectedRowIndex, 2).toString();

                        int soluong = Integer.parseInt(tablelk.getValueAt(selectedRowIndex, 4).toString());
                        double giaban = Double.parseDouble(tablelk.getValueAt(selectedRowIndex, 5).toString());

                        String inputSoluong = JOptionPane.showInputDialog(framelk, "Nhập số lượng:", "Nhập Số Lượng", JOptionPane.PLAIN_MESSAGE);

                        if (inputSoluong != null) {
                            int soluongNhap = Integer.parseInt(inputSoluong);
                            int soluongHienCo = Integer.parseInt(tablelk.getValueAt(selectedRowIndex, 4).toString());

                            if (soluongNhap > 0 && soluongNhap <= soluongHienCo) {
                                double total = soluongNhap * giaban;

                                DefaultTableModel destModel = (DefaultTableModel) tblLinhKien.getModel();
                                destModel.addRow(new Object[]{nextRowID, nhacungcap, linhkien, giaban, soluongNhap, total});
                                ds.add(new Object[]{nhacungcap, linhkien, giaban, soluongNhap, total});
                                Tien = Tien + total;
                                lblTongLK.setText(String.valueOf(Tien));
                                if (!txtCong.getText().isEmpty()) {
                                    try {
                                        TienCc = Double.parseDouble(txtCong.getText());
                                        result = Tien + TienCc;
                                        txtTongTienTT.setText(String.valueOf(result));
                                    } catch (NumberFormatException ex) {
                                        txtTongTienTT.setText(String.valueOf(result));
                                    }
                                } else {
                                    txtTongTienTT.setText(String.valueOf(result));
                                }                               
                                Connection conn = null;
                                PreparedStatement pta = null;
                                try {                                   
                                    String SQL = "UPDATE PHUTUNG SET soluong = soluong - ? WHERE Soluong = ?";
                                    conn = data.ConnecSQL.getDBConnect();
                                    pta = conn.prepareStatement(SQL);
                                    pta.setInt(1, soluongNhap);
                                    pta.setInt(2, soluongNhap);
                                    pta.executeUpdate();
                                } catch (SQLException ex) {
                                    Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
                                } finally {

                                    if (pta != null) {
                                        try {
                                            pta.close();
                                        } catch (SQLException ex) {
                                            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                    }
                                }
                            } else {
                                JOptionPane.showMessageDialog(framelk, "Số lượng không hợp lệ hoặc vượt quá số lượng hiện có!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                            }
                        }

                    }

                }
            });

            framelk.add(btnThem, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(tablelk);
            framelk.add(scrollPane);

            framelk.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            framelk.setLocationRelativeTo(null);
            framelk.pack();
            framelk.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void btnThemPhieuNhan() {
        framepn = new JFrame("Phiếu Sửa ");
        tablepn = new JTable();
        framepn.setPreferredSize(new Dimension(800, 300));
        String[] columnNames = {"masua", "ID", "Họ tên ", "Số Điện Thoại ", "tên Xe ", "Thời Gian ", "Hẹn", " Tình Trạng ", " Nội Dung"};
        DefaultTableModel modelll = new DefaultTableModel(columnNames, 0);

        try {
            ThemPhieuNhanDao Kh = new ThemPhieuNhanDao();
            for (ThemPhieuNhanUse sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[12];
                rowData[0] = sp.getIdRecep();
                rowData[1] = sp.getIdPN();
                rowData[2] = sp.getTenkh();
                rowData[3] = sp.getSdt();
                rowData[4] = sp.getXe();
                rowData[5] = sp.getTimevao();
                rowData[6] = sp.getTimehen();
                rowData[7] = sp.getTinhTrang();
//                rowData[8] = sp.getTongTien();
                rowData[8] = sp.getNoidung();
                modelll.addRow(rowData);
            }
            tablepn.setModel(modelll);

            JButton btnThoat = new JButton("Thoát");
            btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    framepn.dispose(); // Close the JFrame
                }
            });
            framepn.add(btnThoat, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(tablepn);
            framepn.add(scrollPane);

            framepn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            framepn.setLocationRelativeTo(null);
            framepn.pack();
            framepn.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            // Handle any other exceptions here
        }
        buttonpn = new JButton();
        tablepn.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int myindex = tablepn.getSelectedRow();
                txtMaSua.setText(tablepn.getValueAt(myindex, 0).toString());
                txtKhachHang.setText(tablepn.getValueAt(myindex, 2).toString());
                txtXe.setText(tablepn.getValueAt(myindex, 4).toString());
                txtTT.setText(tablepn.getValueAt(myindex, 7).toString());
                txtNoiDung.setText(tablepn.getValueAt(myindex, 8).toString());
                txtSdt.setText(tablepn.getValueAt(myindex, 3).toString());
                txtTimeHen.setText(tablepn.getValueAt(myindex, 6).toString());
                txtNhan.setText(tablepn.getValueAt(myindex, 5).toString());
                txtMpn.setText(tablepn.getValueAt(myindex, 1).toString());
            }
        });
    }

    private void btnThemNhanVien() {
        framenv = new JFrame("Nhân Viên ");
        tablenv = new JTable();
        framenv.setPreferredSize(new Dimension(800, 300));
        String[] columnNames = {"Tên Nhân Viên ", "Giới Tính  ", " Địa Chỉ   "};
        DefaultTableModel modell = new DefaultTableModel(columnNames, 0);

        try {
            NhanVienUse Kh = new NhanVienUse();
            for (NhanVienDao sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[4];
                rowData[0] = sp.getHoten();
                rowData[1] = sp.isGioitinh();
                rowData[2] = sp.getSdt();
                modell.addRow(rowData);
            }
            tablenv.setModel(modell);

            JButton btnThoat = new JButton("Thoát");
            btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    framenv.dispose(); // Close the JFrame
                }
            });
            framenv.add(btnThoat, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(tablenv);
            framenv.add(scrollPane);

            framenv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            framenv.setLocationRelativeTo(null);
            framenv.pack();
            framenv.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            // Handle any other exceptions here
        }
        buttonnv = new JButton();
        tablenv.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int myindex = tablenv.getSelectedRow();
                txtNvpt.setText(tablenv.getValueAt(myindex, 0).toString());

//             txtXe.setText(tablelk.getValueAt(myindex, 3).toString());
            }
        });
    }

    public void LamMoi() {
        txtKhachHang.setText("");
        txtSdt.setText("");
        txtXe.setText("");
        txtMpn.setText("");
        txtTimeHen.setText("");
        txtTT.setText("");
        txtNvpt.setText("");
        DefaultTableModel model = (DefaultTableModel) tblLinhKien.getModel();
        model.setRowCount(0);
        String[] columnNames = {"id", "Tên Nhà Cung Cấp", "Đơn Giá", "Số Lượng", "Tổng Tiền"};
        DefaultTableModel newModel = new DefaultTableModel(columnNames, 0);
        tblLinhKien.setModel(newModel);
        txtNoiDung.setText("");
        txtTongTienTT.setText("");
    }

    private void clock() {
        new Thread() {
            public void run() {
                while (true) {
                    Calendar ca = new GregorianCalendar();
                    int hour = ca.get(Calendar.HOUR);
                    int min = ca.get(Calendar.MINUTE);
                    int AM_PM = ca.get(Calendar.AM_PM);

                    String day_night;
                    if (AM_PM == 1) {
                        day_night = "PM";
                    } else {
                        day_night = "AM";
                    }
                    lblClock.setText(hour + "giờ :" + min + "phút :" + day_night);
                }
            }
        }.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCongsua;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnLinhKien;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnPhieuNhan;
    private javax.swing.JButton btnPhieuSua;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClock;
    private javax.swing.JTextField lblTongLK;
    private javax.swing.JTable tblLinhKien;
    private javax.swing.JTextField txtCong;
    private javax.swing.JTextField txtKhachHang;
    private javax.swing.JTextField txtMaSua;
    private javax.swing.JTextField txtMhd;
    private javax.swing.JTextField txtMpn;
    private javax.swing.JTextField txtNhan;
    private javax.swing.JTextPane txtNoiDung;
    private javax.swing.JTextField txtNvpt;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTT;
    private javax.swing.JButton txtThemMa;
    private javax.swing.JTextField txtTimeHen;
    private javax.swing.JTextField txtTongTienTT;
    private javax.swing.JTextField txtXe;
    // End of variables declaration//GEN-END:variables
}
