/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package duanmau1;

import DAO.Xepn;
import Oop.XeOpp;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import thanhtoan.BntPhieuNhanUse;
import thanhtoan.BtnPhieuNhanDao;
import thanhtoan.CongDao;
import thanhtoan.CongUse;
import thanhtoan.NhanVienDao;
import thanhtoan.NhanVienUse;
import thanhtoan.TaoHoaDon;
import thanhtoan.ThemlinhkienDao;
import thanhtoan.ThemlinhkienUse;

/**
 *
 * @author dauxu
 */
public class PhieuSua extends javax.swing.JFrame {

    private JButton exitButton;
//    Thêm Khách Hàng 
    private JTable table;
    private JPanel panel;
    private JFrame tableFrame;
    private JButton button;
// .........................
    //  Thêm Linh Kiện 
    private JTable tablelk;
    private JPanel panellk;
    private JButton buttonlk;
    private JFrame framelk;

//    Thêm Phiếu Nhận 
    private JTable tablepn;
    private JFrame framepn;
    private JButton buttonpn;
// Thêm Nhân Viên 
    private JTable tablenv;
    private JFrame framenv;
    private JButton buttonnv;
    // Thêm Phiếu Nhận
    private JTable tabletpn;
    private JFrame frametpn;
    private JButton buttontpn;
//    Them Cong 
    private JTable tableCong;
    private JFrame framecong;
    private JButton buttonCong;
/////////////
//    Giờ 
    public static String dataTime;
// Người Thanh Toán 
    public static String dataNTT;
//    Số Điện Thoại 
    public static String dataSDt;
//     Mã Hóa Đơn 
    public static String dataMHD;
//      Tên Khách Hàng 
    public static String dataTKH;
//       Mã Phiếu Nhận 
    public static String dataMPN;
//        Số điện thoại khách hàng 
    public static String dataSDTKH;
//        Biển Số Xe 
    public static String dataBSX;
//        Tên Xe 
    public static String dataTenXe;
//        Ngày Đưa Vào 
    public static String datatimein;
//        Ngày Trả Xe 
    public static String dataout;
// tinh trang xe 
    public static String dataTT;
//    cong sua
    public static String dataCong;
//    phieu sua
    public static String dataSua;
//    tongthanhtoan
    public static String dataTongTien;
    DefaultTableModel LinhKien = new DefaultTableModel();
    ArrayList<Object> ds = new ArrayList<>();

    public String setPN() {
        String kh = new thanhtoan.ThanhToanUse().MaPN();
        return kh;
    }

    public String setMasua() {
        String kh = new thanhtoan.ThanhToanUse().MaKH();
        return kh;
    }

    /**
     * Creates new form PhieuSua
     */
    public PhieuSua() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        btnNeww = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMps = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtNVphutrach = new javax.swing.JTextField();
        txtMph = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMaXe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTimeNhan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTimeHen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMakhach = new javax.swing.JTextField();
        txtTenXe = new javax.swing.JTextField();
        txtBienSo = new javax.swing.JTextField();
        txtTimeBatDau = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDungNhan = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNguyenNhan = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLinhKien = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txtMaCong = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtPhiSuaChua = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtLinhKien = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTong = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh Sách ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jToggleButton1.setText("Danh sách phiếu hẹn");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Người phụ trách ");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Dịch vụ ");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("Danh sách linh kiện");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton5.setText("Lưu Phiếu ");
        jToggleButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNeww.setText("Làm mới ");
        btnNeww.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNeww, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnNeww, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Phiếu Sửa");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Mã Phiếu Sửa : ");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nhân Viên Phụ Trách  : ");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Mã Phiếu Hẹn : ");

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Mã xe :");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Thời Gian Nhận  : ");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Thời Gian Hẹn : ");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Mã Khách :");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Tên Xe : ");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Biển số : ");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Thời gian bắt đầu :");

        jButton2.setText("->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Tình trạng nhận : ");

        jScrollPane1.setViewportView(txtNoiDungNhan);

        jLabel14.setText("Nguyên Nhân :");

        jScrollPane2.setViewportView(txtNguyenNhan);

        tblLinhKien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TT", "Nhà Cung Cấp ", "Linh Kiện", "Đơn Giá ", "Số Lượng ", "Tổng Tiền "
            }
        ));
        jScrollPane3.setViewportView(tblLinhKien);

        jLabel15.setText("Mã Sửa  : ");

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel16.setText("Phí Sửa Chữa : ");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Chưa Xong");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Đã Xong");

        jLabel17.setText("Tình trạng : ");

        jLabel18.setText("Phí Linh Kiện : ");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Tổng : ");

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaCong, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(txtPhiSuaChua)
                    .addComponent(txtLinhKien))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(631, 631, 631)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtMps, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton1))
                            .addComponent(txtMph, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTimeNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTimeHen, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNVphutrach, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(txtMakhach)
                                    .addComponent(txtTenXe)
                                    .addComponent(txtBienSo)
                                    .addComponent(txtTimeBatDau))
                                .addGap(29, 29, 29)
                                .addComponent(jButton4))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(txtNVphutrach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMakhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimeNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBienSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimeHen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimeBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhiSuaChua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        ThemCong();

    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        danhsachphieuhen();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        danhsachlinhkien();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        btnThemNhanVien();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtMps.setEditable(false);
        txtMps.setText(setPN());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String idcar = txtMaXe.getText().trim();
        if (!idcar.isEmpty()) {
            Xepn Xee = new Xepn();
            ArrayList<XeOpp> Xeee = Xee.findXe(idcar);
            if (!Xeee.isEmpty()) {
                XeOpp firstXe = Xeee.get(0);
                txtMakhach.setText(firstXe.getMahk());
                txtTenXe.setText(firstXe.getTenxe());
                txtBienSo.setText(firstXe.getBienso());
            } else {
                // Handle case when no data is found
                txtMakhach.setText("");
                txtTenXe.setText("");
                txtBienSo.setText("");
                JOptionPane.showMessageDialog(this, "No data found for idcar: " + idcar);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Date a = java.sql.Date.valueOf(LocalDate.now());
        txtTimeBatDau.setText(String.valueOf(a));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtMaCong.setEditable(false);
        txtMaCong.setText(setMasua());
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhieuSua().setVisible(true);
            }
        });
    }

    private void New() {
        txtBienSo.setText("");
        txtLinhKien.setText("");
        txtMaCong.setText("");
        txtMaXe.setText("");
        txtMakhach.setText("");
        txtMph.setText("");
        txtMps.setText("");
        txtNVphutrach.setText("");
        txtNguyenNhan.setText("");
        txtNoiDungNhan.setText("");
        txtPhiSuaChua.setText("");
        txtTenXe.setText("");
        txtTimeBatDau.setText("");
        txtTimeHen.setText("");
        txtTimeNhan.setText("");
        txtTong.setText("");
        DefaultTableModel model = (DefaultTableModel) tblLinhKien.getModel();
        model.setRowCount(0);
        String[] columnNames = {"id", "Tên Nhà Cung Cấp", "Đơn Giá", "Số Lượng", "Tổng Tiền"};
        DefaultTableModel newModel = new DefaultTableModel(columnNames, 0);
        tblLinhKien.setModel(newModel);

    }

    private void ThemCong() {
        framecong = new JFrame(" Công ");
        tableCong = new JTable();
        framecong.setPreferredSize(new Dimension(800, 300));
//          button = new JButton();
        String[] columnNames = {"Id", "Tên Công", " Giá "};
        DefaultTableModel modelllllll = new DefaultTableModel(columnNames, 0);

        try {
            CongDao Kh = new CongDao();
            for (CongUse sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[7];
                rowData[0] = sp.getId();
                rowData[1] = sp.getTenCong();
                rowData[2] = sp.getGia();

//                rowData[6] = sp.getTongTien();
                modelllllll.addRow(rowData);
            }
            tableCong.setModel(modelllllll);

            JButton btnThoat = new JButton("Thoát");
            btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
//                    Tien = Tien + total;
//                    lblTongLK.setText(Tien + "");
//                    TienCc = Double.parseDouble(txtCong.getText());
//                    result = Tien + TienCc;
//                    txtTongTienTT.setText(result + "");
                    if (!txtPhiSuaChua.getText().isEmpty()) {
                        try {
                            TienCc = Double.parseDouble(txtPhiSuaChua.getText());
                            result = Tien + TienCc;
                            txtPhiSuaChua.setText(String.valueOf(result));
                        } catch (NumberFormatException ex) {
                            // Handle the exception if the input is not a valid number
//                            txtTongTienTT.setText("Invalid Input");
                            txtPhiSuaChua.setText(String.valueOf(result));
                        }
                    } else {
                        txtPhiSuaChua.setText(String.valueOf(result));
                    }
                    framecong.dispose(); // Close the JFrame
                }
            });
            framecong.add(btnThoat, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(tableCong);
            framecong.add(scrollPane);

            framecong.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            framecong.setLocationRelativeTo(null);
            framecong.pack();
            framecong.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            // Handle any other exceptions here
        }
        buttonCong = new JButton();
        tableCong.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int myindex = tableCong.getSelectedRow();
                txtPhiSuaChua.setText(tableCong.getValueAt(myindex, 2).toString());
                txtMaCong.setText(tableCong.getValueAt(myindex, 0).toString());
            }
        });
    }

    private void btnThemNhanVien() {
        framenv = new JFrame("Nhân Viên ");
        tablenv = new JTable();
        framenv.setPreferredSize(new Dimension(800, 300));
        String[] columnNames = {"Tên Nhân Viên ", "Giới Tính  ", " Địa Chỉ   "};
        DefaultTableModel modell = new DefaultTableModel(columnNames, 0);

        try {
            NhanVienUse Kh = new NhanVienUse();
            for (NhanVienDao sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[4];
                rowData[0] = sp.getHoten();
                rowData[1] = sp.isGioitinh();
                rowData[2] = sp.getSdt();
                modell.addRow(rowData);
            }
            tablenv.setModel(modell);

            JButton btnThoat = new JButton("Thoát");
            btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    framenv.dispose(); // Close the JFrame
                }
            });
            framenv.add(btnThoat, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(tablenv);
            framenv.add(scrollPane);

            framenv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            framenv.setLocationRelativeTo(null);
            framenv.pack();
            framenv.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            // Handle any other exceptions here
        }
        buttonnv = new JButton();
        tablenv.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int myindex = tablenv.getSelectedRow();
                txtNVphutrach.setText(tablenv.getValueAt(myindex, 0).toString());

//             txtXe.setText(tablelk.getValueAt(myindex, 3).toString());
            }
        });
    }

    double Tien = 0;
    double TienCc = 0;
    double result = 0;

    private void danhsachlinhkien() {
        framelk = new JFrame("Linh Kiện  ");
        tablelk = new JTable();
        framelk.setPreferredSize(new Dimension(800, 300));
        String[] columnNames = {"Mã phiếu sửa  ", "Tên Nhà Cung Cấp ", " Linh Kiện  ", " Đơn Giá  ", " Số Lượng ", "Giá Bán "};
        DefaultTableModel modell = new DefaultTableModel(columnNames, 0);

        PreparedStatement pta = null;
        try {

            ThemlinhkienDao Kh = new ThemlinhkienDao();
            for (ThemlinhkienUse sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[6];
                rowData[0] = sp.getMasua();
                rowData[1] = sp.getTencc();
                rowData[2] = sp.getTenPT();
                rowData[3] = sp.getGia();
                rowData[4] = sp.getSoluong();
                rowData[5] = sp.getGiaban();
                modell.addRow(rowData);
            }
            tablelk.setModel(modell);
            JButton btnThoat = new JButton("Thoát");
            btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    frametpn.dispose(); // Close the JFrame
                }
            });
            buttonlk = new JButton();
            JButton btnThem = new JButton("Thêm ");
            btnThem.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {

                    int nextRowID = tblLinhKien.getRowCount() + 1;
                    int selectedRowIndex = tablelk.getSelectedRow();

                    if (selectedRowIndex >= 0) {
                        String nhacungcap = tablelk.getValueAt(selectedRowIndex, 1).toString();
                        String linhkien = tablelk.getValueAt(selectedRowIndex, 2).toString();

                        int soluong = Integer.parseInt(tablelk.getValueAt(selectedRowIndex, 4).toString());
                        double giaban = Double.parseDouble(tablelk.getValueAt(selectedRowIndex, 5).toString());

                        String inputSoluong = JOptionPane.showInputDialog(framelk, "Nhập số lượng:", "Nhập Số Lượng", JOptionPane.PLAIN_MESSAGE);

                        if (inputSoluong != null) {
                            int soluongNhap = Integer.parseInt(inputSoluong);
                            int soluongHienCo = Integer.parseInt(tablelk.getValueAt(selectedRowIndex, 4).toString());

                            if (soluongNhap > 0 && soluongNhap <= soluongHienCo) {
                                double total = soluongNhap * giaban;

                                DefaultTableModel destModel = (DefaultTableModel) tblLinhKien.getModel();
                                destModel.addRow(new Object[]{nextRowID, nhacungcap, linhkien, giaban, soluongNhap, total});
                                ds.add(new Object[]{nhacungcap, linhkien, giaban, soluongNhap, total});
                                Tien = Tien + total;
                                txtLinhKien.setText(String.valueOf(Tien));
                                if (!txtPhiSuaChua.getText().isEmpty()) {
                                    try {
                                        TienCc = Double.parseDouble(txtPhiSuaChua.getText());
                                        result = Tien + TienCc;
                                        txtTong.setText(String.valueOf(result));
                                    } catch (NumberFormatException ex) {
                                        txtTong.setText(String.valueOf(result));
                                    }
                                } else {
                                    txtTong.setText(String.valueOf(result));
                                }

//                               
                                Connection conn = null;
                                PreparedStatement pta = null;
                                try {
                                    String SQL = "UPDATE PHUTUNG SET soluong = soluong - ? WHERE Soluong = ?";
                                    conn = data.ConnecSQL.getDBConnect();
                                    pta = conn.prepareStatement(SQL);
                                    pta.setInt(1, soluongNhap);
                                    pta.setInt(2, soluongNhap);
                                    pta.executeUpdate();
                                } catch (SQLException ex) {
                                    Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
                                } finally {

                                    if (pta != null) {
                                        try {
                                            pta.close();
                                        } catch (SQLException ex) {
                                            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                    }
                                }
                            } else {
                                JOptionPane.showMessageDialog(framelk, "Số lượng không hợp lệ hoặc vượt quá số lượng hiện có!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                            }
                        }

                    }

                }
            });

            framelk.add(btnThem, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(tablelk);
            framelk.add(scrollPane);

            framelk.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            framelk.setLocationRelativeTo(null);
            framelk.pack();
            framelk.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void danhsachphieuhen() {
        frametpn = new JFrame("Phiếu  Hẹn ");
        tabletpn = new JTable();
        frametpn.setPreferredSize(new Dimension(800, 300));
//          button = new JButton();
        String[] columnNames = {"Id", "Mã Xe", "Thời Gian ", "Hẹn ", " Tình Trạng  "};
        DefaultTableModel modellllll = new DefaultTableModel(columnNames, 0);

        try {
            BtnPhieuNhanDao Kh = new BtnPhieuNhanDao();
            for (BntPhieuNhanUse sp : Kh.getAllSanPham()) {
                Object rowData[] = new Object[7];
                rowData[0] = sp.getID();
                rowData[1] = sp.getIdcar();
                rowData[2] = sp.getTime();
                rowData[3] = sp.getTimeout();
                rowData[4] = sp.getTinhTrangIn();
//                rowData[6] = sp.getTongTien();
                modellllll.addRow(rowData);
            }
            tabletpn.setModel(modellllll);

            JButton btnThoat = new JButton("Thoát");
            btnThoat.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    frametpn.dispose(); // Close the JFrame
                }
            });
            frametpn.add(btnThoat, BorderLayout.SOUTH);
            JScrollPane scrollPane = new JScrollPane(tabletpn);
            frametpn.add(scrollPane);

            frametpn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frametpn.setLocationRelativeTo(null);
            frametpn.pack();
            frametpn.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            // Handle any other exceptions here
        }
        buttontpn = new JButton();
        tabletpn.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int myindex = tabletpn.getSelectedRow();
                txtMph.setText(tabletpn.getValueAt(myindex, 0).toString());
                txtTimeHen.setText(tabletpn.getValueAt(myindex, 3).toString());
                txtMaXe.setText(tabletpn.getValueAt(myindex, 1).toString());
                txtTimeNhan.setText(tabletpn.getValueAt(myindex, 2).toString());
                txtNoiDungNhan.setText(tabletpn.getValueAt(myindex, 4).toString());
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnNeww;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JTable tblLinhKien;
    private javax.swing.JTextField txtBienSo;
    private javax.swing.JTextField txtLinhKien;
    private javax.swing.JTextField txtMaCong;
    private javax.swing.JTextField txtMaXe;
    private javax.swing.JTextField txtMakhach;
    private javax.swing.JTextField txtMph;
    private javax.swing.JTextField txtMps;
    private javax.swing.JTextField txtNVphutrach;
    private javax.swing.JTextPane txtNguyenNhan;
    private javax.swing.JTextPane txtNoiDungNhan;
    private javax.swing.JTextField txtPhiSuaChua;
    private javax.swing.JTextField txtTenXe;
    private javax.swing.JTextField txtTimeBatDau;
    private javax.swing.JTextField txtTimeHen;
    private javax.swing.JTextField txtTimeNhan;
    private javax.swing.JTextField txtTong;
    // End of variables declaration//GEN-END:variables
}
